name=PxGraph_ILI9341_Shield
version=1.0.0
author=Olivier Pécheux
maintainer=Olivier <Olivier@Dansetrad.fr>
sentence=Allows Arduino boards to control a screen shield with a ILI9341. For Arduino UNO. For Arduino MEGA.
paragraph=Cette bibliotèque permet de gérer un écran graphique enfichable sur Uno si il est équipé d'un driver ILI9341.
category=Device Control
url=http://arduino.dansetrad.fr/Px_Graph 
architectures=avr
includes=PxGraph_ILI9341_Shield.h